### ISSUE TITLE
http server:  timeouts are not configured

### ISSUE THREAD

**Issue by sergeydobrodey** [paysuper/paysuper-billing-server#392]
Timeouts (ReadTimeout, ReadHeaderTimeout) are not configured for http server. Client connection leaks can lead to exhausting all the file descriptors:

https://github.com/paysuper/paysuper-billing-server/blob/1098dae347184f05232483f05962e7818969b4de/internal/app.go#L281

**Comment by sidmal** [comment]
Hi @sergeydobrodey!
Yes, your right! We are just forgot about it. But it not a critical problem because we use http server in this service only for process health check requests from k8s.
We will add params for configuring http server timeouts in near PR. I will write about it in this issue when we will create PR.

**Comment by misterion** [comment]
The issue was fixed in #396 and should be delivered in next update.
